### PR TITLE
Small adjustments to economic variables

### PR DESCRIPTION
**Pull request by erikfilias**
Changes of units on economic variables according to #76 and #77.

### CODE REVIEW

**Comment by hettieboonman** [comment]
Hi all, 

Is there any progress in accepting these changes? 

Greets, Hettie

**Comment by danielhuppmann** [comment]
I was waiting for a decision on an agreed spelling of Euro, see #85 - please vote there (or suggest an alternative). Then we can close that discussion and continue with the implementation of the changes.

**Comment by danielhuppmann** [comment]
@erikfilias & @sebastianzwickl, per the outcome of the vote in #85, can you please work through the entire nomenclature and harmonize to the new spelling (allowing several currencies where relevant). Also, please keep the orders of magnitude (million, billion) as lower-case for consistency.

**Comment by erikfilias** [comment]
> @erikfilias & @sebastianzwickl, per the outcome of the vote in #85, can you please work through the entire nomenclature and harmonize to the new spelling (allowing several currencies where relevant). Also, please keep the orders of magnitude (million, billion) as lower-case for consistency.

I've just updated the units for all variables in economy.yaml, @hettieboonman & @sebastianzwickl, please check it. 
I also keep EUR/kWh for `Price|Final Energy|Residential|Electricity:`

**Review by sebastianzwickl — APPROVED** [review]

**Review by danielhuppmann — APPROVED** [review]
Thanks @erikfilias!

**Pull request merged**
